languageCode : "ko-kr"
title : "Let'sBe MEDIA"
baseURL : "https://letsbe-media.appspot.com/"
theme: "hugo-tranquilpeak-theme"
menu:
  main:
    weight: 1
    identifier: "About"
    url: "about"
author:
  name: "Let'sBe MEDIA"
  location: "South Korea"
  picture: "https://cdn1.iconfinder.com/data/icons/ninja-things-1/1772/ninja-simple-512.png"
  bio: "스티머즈 스트리머 3대장"
params:
  sidebarBehavior : 1
  thumbnailImage : true
  thumbnailImagePosition : "right"
  autoThumbnailImage : true
  coverImage : "cover.jpg"
  favicon :
  imageGallery : true
  hierarchicalCategories : true
menu:
  main:
    - weight: 1
      identifier: "home"
      name: "Home"
      url: "/"
    - weight: 2
      identifier: "about"
      name: "About"
      url: "/about"
    - weight: 3
      identifier: "contact"
      name: "Contact us"
      url: "https://steamers.slack.com"
